pub const LINK_HEADINGS: &[&str] = &[
    "Related Work",
    "Similar Papers",
    "More from the Authors",
    "See Also",
    "Background and Context",
    "Foundational Research",
    "Connected Studies",
    "Further Reading",
    "Related Approaches",
    "Complementary Work",
    "Additional Resources",
    "Relevant Literature",
    "Exploring Further",
    "Related Investigations",
    "Supporting References",
    "Methodological Foundations",
    "Theoretical Grounding",
];
