name: Checks

on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 14 * * *"
  workflow_call:

permissions:
  contents: read

jobs:
  Checks-and-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - run: rustup toolchain install stable
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - name: Validate Build
        run: cargo build

      - name: Check Formatting
        run: cargo fmt --check

      - name: Clippy!
        run: cargo clippy --no-deps --all-targets

      - name: Run Tests
        run: cargo test

      - name: Verify Publish-Ready
        run: cargo publish --dry-run

  Docker-Image-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v4

      - name: Build Image
        uses: docker/build-push-action@v7
        with:
          push: false
          load: true
          tags: miasma:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker Image
        run: |
          set -euo pipefail

          container_id=$(docker run -d --rm \
            -p 9999:9999 \
            miasma:test \
            --poison-source https://example.com \
          )
          trap 'docker rm -f "$container_id"' EXIT

          sleep 5
          curl -fsS http://localhost:9999
